# Generated by Django 4.2.4 on 2024-10-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0044_alter_goodsmodel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="sorted_ID",
            field=models.IntegerField(blank=True, null=True, verbose_name="Sorted ID"),
        ),
    ]
