# Generated by Django 4.2.4 on 2024-10-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0047_remove_webinfo_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinfo",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
