# Generated by Django 4.2.4 on 2024-10-23 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0050_alter_goodsmodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsmodel",
            options={
                "ordering": ["category"],
                "verbose_name_plural": "3. Product list",
            },
        ),
    ]
